/**
 * Module → allowed actions for designation permissions (ERP admin).
 * Single source for PermissionsModal + DesignationPermissionsPicker.
 */
export const DESIGNATION_MODULE_ACTIONS: Record<string, string[]> = {
  Dashboard: ["view"],

  Employees: ["view", "create", "update", "delete", "change password"],
  Designations: ["view", "create", "update", "delete", "change_permissions"],

  Orders: [
    "view",
    "update",
    "view_all",
    "view_pending",
    "view_incomplete",
    "view_no_response",
    "view_good_but_no_response",
    "view_advance_required",
    "view_hold",
    "view_confirm",
    "view_preorder",
    "view_cancelled",
  ],
  "New Orders": ["create"],
  "Search Orders": ["view"],
  "Delivery Orders": [
    "view",
    "update",
    "view_pending",
    "view_delivered",
    "view_cancelled",
    "view_in_review",
    "view_return_pending",
    "view_return",
    "view_unknown",
    "view_all",
    "view_steadfast",
    "view_pathao",
    "view_office_delivery",
    "view_other",
  ],
  "Warehouse Orders": [
    "view",
    "update",
    "view_pending",
    "view_unprint",
    "view_print",
    "view_shipped",
    "view_steadfast",
    "view_pathao",
    "view_office_delivery",
    "view_other",
  ],

  Products: [
    "view",
    "create",
    "update",
    "delete",
    "review image add",
    "update bom",
    "planning",
    "addons",
    "reviews",
    "duplicate product",
    "update packaging bom",
  ],
  "Combo Products": [
    "view",
    "create",
    "update",
    "delete",
    "review image add",
    "planning",
    "addons",
    "reviews",
    "duplicate product",
    "update packaging bom",
  ],
  Stocks: ["view", "create", "update", "delete"],
  "Product Categories": ["view", "create", "update", "delete"],
  Categories: ["view", "create", "update", "delete"],
  Units: ["view", "create", "update", "delete"],
  Brands: ["view", "create", "update", "delete"],
  Types: ["view", "create", "update", "delete"],
  Addons: ["view", "create", "update", "delete"],
  Review: ["view", "update", "delete"],

  Materials: ["view", "create", "update", "delete"],
  "Requisition List": [
    "view",
    "update",
    "delete",
    "view_all",
    "view_pending",
    "view_approved",
    "view_rejected",
  ],
  "Stock Alert": ["view", "update", "delete"],
  "Purchase Need": ["view", "create"],
  Purchases: ["view", "create", "update", "delete"],
  Returns: ["view"],
  Suppliers: ["view", "create", "update", "delete"],
  "Product Purchase": ["view", "create", "update", "delete"],
  "Production Stock List": ["view", "update", "delete"],
  "Production List": ["view", "update", "delete"],

  Sales: ["view", "create", "update", "delete"],
  "Customer List": ["view", "create", "update", "delete"],

  Profile: ["view", "update"],
  "Media Library": ["view", "create", "update", "delete"],
  Warehouses: ["view", "create", "update", "delete"],
  Vat: ["view", "create", "update", "delete"],
  "Blogs List": ["view", "create", "update", "delete"],

  "Content Management": ["view", "update"],
  "Hot Deals": ["view", "create", "update", "delete"],

  "Sales Report": [
    "view",
    "view_filter",
    "view_summary",
    "view_product_overview",
    "view_status_distribution",
    "view_customer_loyalty",
    "view_payment_methods",
    "view_sales_transactions",
    "view_top_customers",
    "view_category_performance",
    "view_revenue_breakdown",
    "view_discount_analysis",
  ],
  "Employee Sales Report": [
    "view",
    "view_employee_report",
    "view_performance_report",
    "view_web_order_updates",
    "view_order_cancellations",
    "view_work_log",
    "view_order_completions",
    "view_order_status_sub",
    "view_order_sources_sub",
    "view_product_report_sub",
    "view_other_sub",
    "view_all_sub",
  ],
  "Order Report": [
    "view",
    "view_combined",
    "view_order_report",
    "view_district_map",
    "view_status_updates",
    "view_web_order",
  ],
  "Product Report": [
    "view",
    "view_product_report",
    "view_product_status",
    "view_purchase_history",
    "view_inventory_report",
    "view_product_a_z",
  ],
  "Business Report": ["view"],
  "Purchase Report": [
    "view",
    "view_today",
    "view_weekly",
    "view_monthly",
    "view_yearly",
    "view_all",
  ],
  "Profit & Sales Report": [
    "view",
    "view_summary",
    "view_sales",
    "view_delivered_orders",
    "view_profit_sales_chart",
  ],
  "Call Center Follow-ups": ["view", "schedule-follow-up", "view-call-history"],
  "Auto SMS": ["view", "create", "update", "delete"],

  Comments: ["view", "delete"],
  "Delivery Charge": ["view", "create", "update", "delete"],
  Coupons: ["view", "create", "update", "delete"],
  "Order Source": ["view", "create", "update", "delete"],
  "Shipping Note": ["view", "create", "update", "delete"],
};

export const DESIGNATION_MODULE_KEYS = Object.keys(DESIGNATION_MODULE_ACTIONS);
